version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: projectplanning_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-projectplanning}
      MYSQL_USER: ${DB_USER:-projectuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-projectpass}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - projectplanning_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD:-rootpassword}"]
      timeout: 20s
      retries: 10

  # Backend Application
  backend:
    build: .
    container_name: projectplanning_backend
    restart: unless-stopped
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${DB_NAME:-projectplanning}
      - DB_USER=${DB_USER:-projectuser}
      - DB_PASSWORD=${DB_PASSWORD:-projectpass}
      - BONITA_SERVER_URL=${BONITA_SERVER_URL:-http://localhost:8080}
      - BONITA_USERNAME=${BONITA_USERNAME:-install}
      - BONITA_PASSWORD=${BONITA_PASSWORD:-install}
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
    volumes:
      - ./logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - projectplanning_network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Adminer (Database Management UI)
  adminer:
    image: adminer:latest
    container_name: projectplanning_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - projectplanning_network
    environment:
      ADMINER_DEFAULT_SERVER: mysql

volumes:
  mysql_data:
    driver: local

networks:
  projectplanning_network:
    driver: bridge