version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: project-planning-mysql-dev
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    ports:
      - "$MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT"
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - project-planning-network
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    container_name: project-planning-backend-dev
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "$NODE_LOCAL_PORT:$NODE_DOCKER_PORT"
    environment:
      - DB_HOST=mysql
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - NODE_DOCKER_PORT=$NODE_DOCKER_PORT
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    networks:
      - project-planning-network
    stdin_open: true
    tty: true
    command: npm start

volumes:
  mysql_data_dev:

networks:
  project-planning-network:
    driver: bridge